#!/usr/bin/env python3
"""Merge all Part 1 knowledge chapters into one complete version."""

import sys, re
sys.path.insert(0, '/workspace/scripts')
from template_engine import save_knowledge_html, save_test

def extract_body(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()
    # Extract content between <body> and first <script> or </body>
    m = re.search(r'<body[^>]*>(.*?)(?:<script|</body>)', html, re.DOTALL)
    if m:
        body = m.group(1)
        # Remove H1 and TOC (will be regenerated by template engine)
        body = re.sub(r'<h1[^>]*>.*?</h1>', '', body, flags=re.DOTALL)
        body = re.sub(r'<div class="toc">.*?</div>', '', body, flags=re.DOTALL)
        return body.strip()
    return ''

knowledge_files = [
    '/workspace/output/生物化学_第1章_绪论_知识精讲.html',
    '/workspace/output/生物化学_第2-5章_知识精讲.html',
    '/workspace/output/生物化学_第6-9章_知识精讲.html',
    '/workspace/output/生物化学_第10-13章_知识精讲.html',
    '/workspace/output/生物化学_第14-18章_知识精讲.html',
]

all_bodies = []
for fp in knowledge_files:
    b = extract_body(fp)
    if b:
        all_bodies.append(b)
        print(f'  ✅ 已提取: {fp}')
    else:
        print(f'  ❌ 提取失败: {fp}')

combined = '\n\n'.join(all_bodies)

save_knowledge_html(combined,
    '/workspace/output/生物化学_第一篇_知识精讲_完整版.html',
    '生物化学 第一篇 结构生物化学 — 知识精讲（全18章）')

print('\n✅ 完整版知识精讲已生成')

# ─── Merge tests ─────────────────────────────────────────────
test_files = [
    '/workspace/output/生物化学_第1章_绪论_自测题.html',
    '/workspace/output/生物化学_第2-5章_自测题.html',
    '/workspace/output/生物化学_第6-9章_自测题.html',
    '/workspace/output/生物化学_第10-13章_自测题.html',
    '/workspace/output/生物化学_第14-18章_自测题.html',
]

import json

def extract_questions(filepath):
    """Extract questions JSON array from test HTML."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    # Pattern: var Q = [...];\nvar LABELS = ...
    m = re.search(r'(?:var|const)\s+Q\s*=\s*(\[.*\]);\s*(?:var|const)\s+LABELS', content, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    # Alternative: const QUESTIONS = [...];
    m2 = re.search(r'const QUESTIONS\s*=\s*(\[.*\]);\s*var LABELS', content, re.DOTALL)
    if m2:
        try:
            return json.loads(m2.group(1))
        except json.JSONDecodeError:
            pass
    return None

all_qs = []
for fp in test_files:
    qs = extract_questions(fp)
    if qs:
        all_qs.extend(qs)
        print(f'  ✅ 已提取 {len(qs)} 题: {fp}')
    else:
        print(f'  ❌ 提取失败: {fp}')

if all_qs:
    save_test(all_qs,
        '/workspace/output/生物化学_第一篇_自测题.html',
        title='生物化学 第一篇 结构生物化学 — 互动自测题（综合卷）',
        subtitle=f'共{len(all_qs)}题 | 涵盖第1-18章 | 建议用时90分钟',
        duration_minutes=90)
    print(f'\n✅ 综合自测题已生成，共 {len(all_qs)} 题')

print('\n📂 所有文件位于 /workspace/output/')